# Generated by Django 2.0.4 on 2018-04-10 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0003_auto_20180410_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
