# Generated by Django 2.0.4 on 2018-04-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0004_auto_20180410_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amper',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='volt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='watt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='watt_hour',
            field=models.FloatField(default=0),
        ),
    ]
