# Generated by Django 2.0.4 on 2018-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon', '0005_auto_20180410_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amper',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='volt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='watt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='watt_hour',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
